server:
  servlet:
    context-path: /api

spring:
  profiles:
    default: local
  output:
    ansi:
      enabled: always

  
  # swagger \uAD00\uB828 \uC124\uC815
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  # Mail 인증
  mail:
    # Google smtp server 사용
    host: smtp.gmail.com
    port: 587
    username: ${auth.smtp.username} #앱 비밀번호 발급받은 google 계정
    password: ${auth.smtp.password} #발급받은 앱 비밀번호
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
          timeout: 5000


  # JPA
  jpa:
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true

# hibernate logging
logging:
  level:
    org.hibernate: info

token:
  accesskey: ${auth.accesskey}
  refreshkey: ${auth.refreshkey}
  datakey: ${auth.datakey}



# charset
# server.servlet.encoding.charset=UTF-8
# server.servlet.encoding.force=true