server:
  port: ${env.server.port}
  error:
    include-exception: false
    include-message: always
    include-stacktrace: on_param
    whitelabel.enabled: true

spring:
  config:
    activate:
      on-profile: local
  # MySQL
  datasource:
    driver-class-name: ${db.mysql.driver}
    url: ${db.mysql.url}
    username: ${db.mysql.username}
    password: ${db.mysql.password}
  # SERVER AUTO RELOAD
  devtools:
    livereload.enabled: true
  freemarker:
    cache: false
  # JPA for auto reload
  jpa:
    show-sql: false
    hibernate.ddl-auto: ${jpa.ddl.option}
