server:
  servlet:
    context-path: /api
    # file upload
    multipart:
      enabled: true
      max-file-size: 200MB

spring:
  profiles:
    default: local
  output:
    ansi:
      enabled: always
  
  # swagger \uAD00\uB828 \uC124\uC815
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  # JPA
  jpa:
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true

# hibernate logging
logging:
  level:
    org.hibernate: info

# app file path
app:
  fileupload:
    #    uploadPath: "/var/lib/jenkins/area_deploy/jiniworld/upload-images/"
    uploadPath: "/static/upload"

# charset
# server.servlet.encoding.charset=UTF-8
# server.servlet.encoding.force=true



