server:
  port: ${env.dev.port}

# java -jar -Dspring.profiles.active=dev *.jar
spring:
  config:
    activate:
      on-profile: dev
  # MySQL
  datasource:
    driver-class-name: ${dev.mysql.driver}
    url: ${dev.mysql.url}
    username: ${dev.mysql.username}
    password: ${dev.mysql.password}
  # Jpa
  jpa:
    hibernate.ddl-auto: ${dev.ddl.option}

# app file path
app:
  file:
    path: ${app.file.path}
